#29 Fix: deploy test 17

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,11 +19,16 @@ jobs:
           java-version: '17'
           cache: 'gradle'
 
-      - name: Create application.yml in build context
+      - name: Create application.yml
         run: |
           mkdir -p src/main/resources
           echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
         shell: bash
+
+      - name: Ensure application.yml exists before Docker build
+        run: |
+          ls -l src/main/resources/application.yml || echo "application.yml not found!"
+          cp src/main/resources/application.yml .
 
       - name: Build with Gradle
         run: |
